### ISSUE TITLE
NodeBipartiteObs object has no attribute variable_features

### ISSUE THREAD

**Issue by prachi-shah-opt** [ds4dm/ecole#345]
## Describe the bug
I am trying to run the example for branching-imitation (https://github.com/ds4dm/ecole/tree/master/examples/branching-imitation) and am getting the following error - 'ecole.core.observation.NodeBipartiteObs' object has no attribute 'variable_features'

Detailed log - 
Traceback (most recent call last):
  File "/home/pshah398/LearningToBranch/EcoleGasseEtAl/branching-imitation/example.py", line 408, in <module>
    observation = train_data[0].to(DEVICE)
  File "/home/pshah398/anaconda3/envs/ecole_env/lib/python3.10/site-packages/torch_geometric/data/dataset.py", line 197, in __getitem__
    data = self.get(self.indices()[idx])
  File "/home/pshah398/LearningToBranch/EcoleGasseEtAl/branching-imitation/example.py", line 235, in get
    variable_features = sample_observation.variable_features
AttributeError: 'ecole.core.observation.NodeBipartiteObs' object has no attribute 'variable_features'

## Setting
- OS: Linux
- Python version: 3.10.5
- Ecole version: 0.7.3

## To Reproduce
Run the file example.ipynb at https://github.com/ds4dm/ecole/tree/master/examples/branching-imitation

**Comment by rezabayani** [comment]
Have you tried row_features and column_features?
